### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by gerbsen** [route360/r360-java#1]
http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

**Comment by gerbsen** [comment]
1) keypair generieren und public key publishen
2) einige extra felder in pom.xml zufugen (description, scm, developers)
3) unterschreiben und publizieren: das geht durch einige plugins die man in pom.xml configuriert

**Comment by gerbsen** [comment]
@imtezcan I just found this issue :)

**Comment by gerbsen** [comment]
it's done right?

**Comment by imtezcan** [comment]
yep, all fine. can be closed.
